name: Build and Deploy Vite + Vue App

on:
  push:
    branches:
    - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Type-check and build the app
        run: npm run build

      - name: Set SSH key & known_host
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          chmod 600 ~/.ssh/id_rsa

      - name:   deploy build to Lightsail server
        env:
          BUILD_NUMBER: ${{ github.run_number }}
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << EOF
            set -e
            PROJECT_PATH="/home/bitnami/stack/project/frontend/"
            BACKUP_PATH="/home/bitnami/temp"
            BUILD_TAG="build-${BUILD_NUMBER}"

            # Create temp directory if it doesn't exist
            mkdir -p \$BACKUP_PATH

            cd \$PROJECT_PATH || exit

            # Backup old files if dist exists
            if [ "\$(ls -A \$PROJECT_PATH)" ]; then
              zip -r "\$BACKUP_PATH/\$BUILD_TAG.zip" ./*
              rm -rf ./*
            fi
          EOF

          # Upload new build
          scp -i ~/.ssh/id_rsa -r dist/* ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/bitnami/stack/project/frontend/
