name: Build and Deploy Vite + Vue Apps

on:
  push:
    branches:
    - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Type-check and build the app
        run: npm run build

      - name: Set SSH key & known_host
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          chmod 600 ~/.ssh/id_rsa

      - name:   deploy build to Lightsail server
        env:
          BUILD_NUMBER: ${{ github.run_number }}
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}
          chmod +x .github/scripts/backup.sh
          sh ./.github/scripts/backup.sh

          # Upload new build
          scp -i ~/.ssh/id_rsa -r dist/* ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/bitnami/stack/project/frontend/
